### ISSUE TITLE
Outdated Information on the Readme

### ISSUE THREAD

**Issue by LinuxMint4Ever** [nalquas/vokey#1]
Assuming that you intend to keep the file `vokey.sh` for the purpose of running your program, you may want to change the instructions on the main readme.

**Comment by nalquas** [comment]
I agree, that seems more streamlined.
I corrected the readme in https://github.com/nalquas/vokey/commit/b8bc505a92861285feae4272230a5bda06162a47.

**Comment by LinuxMint4Ever** [comment]
Yay!

**Comment by nalquas** [comment]
Okay, this will be the temporary icon for now:
![vokey](https://user-images.githubusercontent.com/22664233/81831112-3dc3b080-953d-11ea-8600-a28ad2d63da5.png)
Certainly not a work of art, but it gets the job done (barely).
